---
apiVersion: v1
kind: Service
metadata:
  name: dns-default-lb
  namespace: openshift-dns
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "3"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "3"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "10"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "10"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "TCP"
    # see https://aws.amazon.com/blogs/containers/how-to-route-udp-traffic-into-kubernetes/
    # the TCP port for the service is the same as the UDP
    # healthcheck must be performed against TCP, but we route UDP because de OpenShift DNS operator is not supporting force_tcp
spec:
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: dns
  selector:
    dns.operator.openshift.io/daemonset-dns: default
  type: LoadBalancer
