---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-deployment
spec:
  replicas: 3  # Number of desired replicas
  selector:
    matchLabels:
      app: sample-whoami
  template:
    metadata:
      labels:
        app: sample-whoami
    spec:
      hostname: sample-whoami
      subdomain: sample-whoami-peer
      containers:
      - name: whoami-container  # Unique container name
        image: traefik/whoami
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080  # Container port set to 8080
        command:
          - "/whoami"
          - "--port=8080"  # Parameter for whoami, modified to listen on port 8080
          - "--name=$(POD_NAME)"  # Using $(POD_NAME) to refer to the current pod's name
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name  # Retrieves the current pod's name
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: sample-whoami
  clusterIP: None  # Headless service to access pods directly
