# This workflow updates an artifact containing the ROSA versions, it's used by renovate
name: Save ROSA Versions as an artifact

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/artifact-rosa-versions.yml

jobs:
  save-rosa-versions:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

    - name: Install ROSA CLI and output rosa versions
      shell: bash
      run: |
        curl -LO "https://mirror.openshift.com/pub/openshift-v4/clients/rosa/latest/rosa-linux.tar.gz"
        tar -xvf rosa-linux.tar.gz
        sudo mv rosa /usr/local/bin/rosa
        chmod +x /usr/local/bin/rosa
        rm -f rosa-linux.tar.gz
        rosa version
        rosa list versions --output json | jq '.[].raw_id' --raw-output > rosa_versions.txt

    - name: Upload ROSA versions artifact
      uses: actions/upload-artifact@v4
      with:
        name: rosa-versions
        path: rosa_versions.txt
