---
name: Pull Request Labeler
on:
    pull_request_target:
    schedule:
        - cron: 0 1 * * 1
    pull_request:
        paths:
            - .github/workflows/labeler.yml

jobs:
    labeler:
        permissions:
            contents: read
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5

            - name: Notify in Slack in case of failure
              id: slack-notification
              if: failure() && github.event_name == 'schedule'
              uses: camunda/infraex-common-config/.github/actions/report-failure-on-slack@b95c5e92a23ad7a2ad0351eeac24e7a2af9ba1b7 # 1.3.4
              with:
                  vault_addr: ${{ secrets.VAULT_ADDR }}
                  vault_role_id: ${{ secrets.VAULT_ROLE_ID }}
                  vault_secret_id: ${{ secrets.VAULT_SECRET_ID }}
