name: Check external links

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 3 1 * *"

jobs:
  lint:
    name: links-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Get Current Timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date +%s)" >> "$GITHUB_ENV"

      - name: Restore lychee cache
        uses: actions/cache@v3
        with:
          path: .lycheecache
          key: "cache-lychee-${{ env.TIMESTAMP }}"
          restore-keys: cache-lychee-

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          fail: true
          args: -c ./lychee-links.toml --base . --cache --max-cache-age 1d . --verbose --no-progress '*.md' './**/*.md'
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Create Issue From File
        if: ${{ github.event_name == 'schedule' && env.lychee_exit_code != 0 }}
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
